title: NeuroTube
description: A platform for simulating and visualizing neural networks and neuron behavior. Explore, analyze, and experiment with neuron models to understand brain functions and computational neuroscience.
theme: minima
.site-header {
  background: url("/header.png") no-repeat center center;
  background-size: cover;
  height: 250px; /* Adjust the height as needed */
}

